  server:
    port: 8080

  spring:
    datasource:
      initialization-mode: always
      platform: postgresql
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/database_777
      username: postgres
      password: AK1126096vb
